# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-robots-configmap
# data:
#   robots.txt: |-
#   {{- if eq .Values.deployment "dev" -}}
# {{ tpl (.Files.Get "robots/dev_robots.txt") . | indent 4 }}
#   {{- else if eq .Values.deployment "qa" -}}
# {{ tpl (.Files.Get "robots/dev_robots.txt") . | indent 4 }}
#   {{- else if eq .Values.deployment "stage" }}
# {{ tpl (.Files.Get "robots/dev_robots.txt") . | indent 4 }}
#   {{- else if eq .Values.deployment "prod" }}
# {{ tpl (.Files.Get "robots/robots.txt") . | indent 4 }}
#   {{- else if eq .Values.deployment "test" }}
# {{ tpl (.Files.Get "robots/robots.txt") . | indent 4 }}
#   {{- end -}}