name: Dev build and deployment

on:
  push:
    branches:
      - development

env:
  NEXT_PUBLIC_APP_ENV: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18


      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Generate Version
        id: version
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build
        if: success()
        run: |
          docker build . -t xapihub/xventure:microsite-v2-${VERSION}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'library'
          output: 'report.txt'

      - name: Upload Dev Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Vulnerability Report
          path: ./report.txt
          retention-days: '90'

      - name: Docker Push
        if: success()
        run: |
          docker push xapihub/xventure:microsite-v2-${VERSION}

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

  deploy:
    runs-on: dev-runner
    needs: build

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Print version
      run: |
        echo "VERSION=${{ needs.build.outputs.VERSION }}" > ${GITHUB_ENV}
        echo "${VERSION}"

    - name: Install helm chart
      run: helm upgrade --install --set image.tag=microsite-v2-${{ env.VERSION }} microsite-v2 .kube --wait -n dev

    - name: Rollback deployment on fail
      if: failure()
      run: helm rollback microsite-v2 -n dev
